### ISSUE TITLE
It's not working.

### ISSUE THREAD

**Issue by workaholicdev** [hotchemi/StringPicker#2]
Hi.
I integrated this library into a new project and do it as your request.
And now I got a problem like this.
Error:Execution failed for task ':app:processDebugManifest'.

> Manifest merger failed : uses-sdk:minSdkVersion 14 cannot be smaller than version L declared in library com.android.support:appcompat-v7:21.0.0-rc1
> What is the problem? I tried to fix the problem by upgrading dependencies, but still not worked.
> If you give me the real working project, I'd appreciate.
> Thank you.

**Comment by hotchemi** [comment]
Hi, I send you email with my opinion.
